# PlateResort Configuration
resort:
  # Hardware settings
  device: "/dev/ttyUSB0"
  baudrate: 57600
  motor_id: 1
  
  # Physical layout
  hotels: ["A", "B", "C", "D"]
  rooms_per_hotel: 20
  
  # Positioning
  offset_angle: 19  # Base offset angle in degrees
  rotation_direction: 1  # 1 for clockwise, -1 for counter-clockwise
  
  # Hotel positions computed dynamically:
  # angle_i = offset_angle + i * (360 / len(hotels)) * rotation_direction
  
  # Movement settings
  default_speed: 50  # Profile velocity (50 = ~5% speed)
  position_tolerance: 0.5  # Position accuracy in degrees
  movement_timeout: 20  # Max wait time in seconds
  
  # Two-stage precise movement (coarse position -> PWM pulses)
  enable_precise_move: true            # Master toggle for two-stage strategy
  switch_error: 3.0                    # Residual error (deg) to switch to pulses (if not already within tolerance)
  stage1_timeout: 8.0                  # Optional coarse stage cap (seconds); set null to disable
  poll_interval: 0.3                   # Coarse stage poll interval (s)
  
  # Pulse stage parameters
  pulse_pwm_start: 180                 # Starting PWM magnitude
  pwm_step: 25                         # Increment when motion small
  pwm_max: 600                         # Ceiling for PWM
  pulse_duration: 0.30                 # On-time (s)
  pulse_rest: 0.20                     # Off-time (s)
  pulse_max: 25                        # Safety cap on pulses
  motion_threshold: 0.12               # Minimum deg motion to count as effective
  stall_pulses: 6                      # Consecutive low-motion pulses to declare stall
  
  # Adaptive backoff (reduce PWM when single pulse moves too much near target)
  enable_backoff: true
  max_step_factor: 1.5                 # Allow at most tolerance * factor per pulse
  pwm_backoff_step: 60                 # Amount to reduce PWM on oversize movement
  
  # Logging verbosity for precise moves
  precise_log: true                    # Print per-pulse telemetry lines
  
  # Torque settings
  goal_torque: 1023  # Max torque output (0-1023, 1023 = 100%)
  torque_limit: 1023  # Torque limit for safety (0-1023)
  
  # Health monitoring
  temperature_limit: 70  # Temperature warning threshold (°C)
  current_limit: 2000  # Current warning threshold (mA)
  voltage_min: 10.0  # Minimum voltage warning (V)
  voltage_max: 14.0  # Maximum voltage warning (V)
  
  # Advanced motor settings
  profile_acceleration: 0  # 0 = default acceleration
  moving_threshold: 10  # Movement detection threshold

# Prefect Configuration
prefect:
  # Workflow settings
  server_host: "0.0.0.0"
  server_port: 4200
  
  # Work pool settings
  # Default value kept for backward compatibility. You can override at runtime
  # by setting the PLATE_RESORT_POOL environment variable.
  work_pool_name: "plate-resort-pool"
  worker_name: "plate-resort-worker"
  
  # Flow settings
  default_retries: 3
  retry_delay_seconds: 5